name: SBOM and Security Audit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Workflow can be triggered manually
  workflow_dispatch:

jobs:

  # Erstellt die SBOM und führt einen Schwachstellenscan durch
  sbom:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v6

    # Liest die Core-Version aus dem NSIS-Installer-Skript
    - name: Get software version
      run: |
        cd CRI_Client
        VER_MAJOR=`grep -E -o "SWVersionMajor[[:blank:]]+=[[:blank:]][[:digit:]]+" MainForm.cs | sed "s/[^0-9.]*//g"`
        VER_MINOR=`grep -E -o "SWVersionMinor[[:blank:]]+=[[:blank:]][[:digit:]]+" MainForm.cs | sed "s/[^0-9.]*//g"`
        VER_PATCH=`grep -E -o "SWVersionPatch[[:blank:]]+=[[:blank:]][[:digit:]]+" MainForm.cs | sed "s/[^0-9.]*//g"`
        echo "Software version '$VER_MAJOR.$VER_MINOR.$VER_PATCH' detected"
        echo "SW_VERSION=$VER_MAJOR.$VER_MINOR.$VER_PATCH" >> $GITHUB_ENV

    # SBOM erstellen
    # Wie man die packages.lock.json bekommt: https://devblogs.microsoft.com/dotnet/enable-repeatable-package-restores-using-a-lock-file/
    - uses: sbomify/sbomify-action@master
      env:
        LOCK_FILE: ${{ github.workspace }}/CRI_Client/packages.lock.json
        OUTPUT_FILE: sbom.cdx.json
        COMPONENT_NAME: CRI-DemoClient
        COMPONENT_VERSION: ${{ env.SW_VERSION }}
        # Produkt- und Firmeninfo werden aus sbomify.json geladen
        AUGMENT: true
        # Metadaten aus Paket-Registry hinzufügen
        ENRICH: true
        # Metadaten aus additional_packages.txt hinzufügen
        #ADDITIONAL_PACKAGES_FILE: ${{ github.workspace }}/additional_packages.txt
        UPLOAD: false

    - name: Export SBOM
      uses: actions/upload-artifact@v7
      with:
        path: sbom.cdx.json
        archive: false

    - uses: actions/setup-go@v6

    - name: Install SBOM QA tool
      run: go install github.com/interlynk-io/sbomqs@latest

    - name: SBOM quality score
      run: sbomqs score sbom.cdx.json

    # Checks compliance with the latest version of BSI TR-03183-2
    - name: Check CRA compliance
      run: sbomqs compliance --bsi --color sbom.cdx.json

    - name: List component licenses
      run: sbomqs list --feature comp_with_declared_license --show sbom.cdx.json

    # TODO: Nicht CRA-konforme Felder füllen

    # Security Audit
    - name: Scan for vulnerabilities
      uses: anchore/scan-action@v7
      with:
        sbom: sbom.cdx.json
        cache-db: true
